# Generated by Django 4.0.3 on 2022-03-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='images/')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB-')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('admission_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('february', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('march', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('april', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('may', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('june', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('july', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('august', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('september', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('october', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('november', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('december', models.CharField(choices=[('paid', 'paid'), ('not_Paid', 'not_paid'), ('not_updated_yet', 'not_updated_yet')], default='not_updated_yet', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
