# Generated by Django 4.0.3 on 2022-07-20 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_address_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='images/classes/')),
                ('age', models.CharField(choices=[('1-5 Years', '1-5 Years'), ('1-10 Years', '1-10 Years'), ('1-15 Years', '1-15 Years'), ('1-20 Years', '1-20 Years'), ('All Ages Student', 'All Ages Student')], max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
