# Generated by Django 4.0.3 on 2022-07-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classes_group_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date',
        ),
    ]
