# Generated by Django 4.0.3 on 2022-07-20 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_group_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
